id: P99E8AEFF
initial_creation_type: input
source_metadata:
  title: Jamyang Loter Wangpo Series
  language: bo
  description: 'Texts by and about Jamyang Loter Wangpo (''jam dbyangs blo gter dbang
    po, 1847–1914):'
  volume:
    b2413bd81d234bacbfbec8f9619c2f32:
      title: Commentary on Nāgārjuna's Verses on the Essence of Dependent Origination
      parent: Buddhist Philosophy
    2d3f4c6b1632413babc1d799c245b079:
      title: Guru Yoga
      parent: Guru Yoga
    20fb64ccbc1b42179b9830195cb42a59:
      title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
      parent: Praise
    b1e6f2188dc04a639ae0cd9c49e268a8:
      title: Prayer to My Root Guru, Jamyang Loter Wangpo
      parent: Prayers
    3d4c9992c9f14d938d6e97b7bbec722a:
      title: Regularly Recitable Prayer to the Root Guru, Loter Wangpo
      parent: Prayers
    f2788c94c6b847deabaee3ae445fe541:
      title: A Song of Prayer to Jamyang Loter Wangpo
      parent: Songs
    12d2f46fe1574e80a7f1a89be2109cf2:
      title: Lament Composed in a State of Deep Sadness
      parent: Songs
    24462d4b266a433898be7a80c3df9d1a:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    4eba267ad09e45559776439d6b67d938:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:59:31.594570'
last_modified_at: '2022-02-28T23:59:31.594572'
statistics:
  total_words: 2853
  total_non_words: 231
quality:
  non_words_ratio: 0.08
